### ISSUE TITLE
0.0.5 version ;)

### ISSUE THREAD

**Issue by theundefined** [Remitly/verdaccio-s3-storage#10]
There are changes for support non-amazon s3 implementation. It would be nice to release a new version in npm :-) (i spend some time to check why s3ForcePathStyle is not working)

**Comment by juanpicado** [comment]
@apexskier the last commit was almost one year ago. Do you need help with this plugin?

**Comment by apexskier** [comment]
Hey, I've totally missed all the issues and PRs on this repo, I unwatched it somehow! I'll try to get a few addressed/merged.

**Comment by apexskier** [comment]
Just released v0.1.0 (minor bump because of a new config option)
