### ISSUE TITLE
What happens in the case of parallel writes?

### ISSUE THREAD

**Issue by dhermes** [Remitly/verdaccio-s3-storage#23]
First, thank you @Remitly for this great `verdaccio` extension package.

I'm curious if there is some mitigation or strategy in place? I.e. if multiple ~hosts~ workers are running `verdaccio` and two hosts try to write to the bucket for `npm publish` and there is a file collision.

**Comment by apexskier** [comment]
We don't have a mitigation strategy for that. We run verdaccio as a single instance so it hasn't been an issue. The main place I can see potential problems is writing to a package's `package.json` file. `.tar.gz` files should be safe to overwrite.

**Comment by dhermes** [comment]
Thanks for the quick response. My hope / guess is that writes are so much less common than reads that this shouldn't matter.

**Comment by dhermes** [comment]
Feel free to close?
